version: '3'
services:
  crosstoolbuildcompiler:
    image: 139.9.186.120:8080/crosstool_build_compiler:latest
    container_name: crosstool_build_compiler
    restart: unless-stopped
    command: /bin/bash
    stdin_open: true
    tty: true
    #devices:
    #  - /dev/ttyUSB0:/dev/ttyUSB0
    volumes:
      - ./workdir:/root/workdir
